"""Fit equivariant completely-positive compressions of the indexed Hessian.

The variation space is two copies (mass and position) of spin two.  Every
SO(3)-equivariant CP compression back to spin two is generated by the five
irreducible Kraus channels in End(H_2) = H_0 + ... + H_4.  This script tests
whether their images can cancel to the fermionic cap operator.
"""

from __future__ import annotations

import numpy as np
import cvxpy as cp
from scipy.optimize import brentq

from weighted_certificate_fermion_cap import (
    BASIS,
    cap_matrix,
    coupled_mass_position_hessian,
    quadratic_mass_matrix,
)


def spin_two_generators() -> list[np.ndarray]:
    generators = []
    for left, right in ((0, 1), (0, 2), (1, 2)):
        omega = np.zeros((3, 3))
        omega[left, right] = 1
        omega[right, left] = -1
        matrix = np.zeros((5, 5))
        for column, source in enumerate(BASIS):
            image = omega @ source - source @ omega
            for row, target in enumerate(BASIS):
                matrix[row, column] = np.sum(target * image)
        generators.append(matrix)
    return generators


def kraus_channels() -> list[list[np.ndarray]]:
    generators = spin_two_generators()
    induced = [
        np.kron(generator, np.eye(5)) + np.kron(np.eye(5), generator)
        for generator in generators
    ]
    casimir = -sum(generator @ generator for generator in induced)
    eigenvalues, eigenvectors = np.linalg.eigh(casimir)
    channels = []
    for ell in range(5):
        vectors = eigenvectors[:, np.abs(eigenvalues - ell * (ell + 1)) < 1e-8]
        assert vectors.shape[1] == 2 * ell + 1
        channels.append(
            [vectors[:, index].reshape(5, 5) for index in range(vectors.shape[1])]
        )
    return channels


CHANNELS = kraus_channels()


def cp_image(channel: list[np.ndarray], matrix: np.ndarray) -> np.ndarray:
    return sum(kraus.T @ matrix @ kraus for kraus in channel)


def random_data(count: int = 80, atoms: int = 5, seed: int = 20260820):
    rng = np.random.default_rng(seed)
    rows = []
    targets = []
    upper = np.triu_indices(5)
    for _ in range(count):
        points = rng.normal(size=(atoms, 3))
        points /= np.linalg.norm(points, axis=1)[:, None]
        weights = rng.dirichlet(np.ones(atoms))
        _, mass, cross, position = coupled_mass_position_hessian(points, weights)
        columns = []
        for channel in CHANNELS:
            for matrix in (mass, cross + cross.T, position):
                columns.append(cp_image(channel, matrix)[upper])
        gram = points @ points.T
        kernel = 32 * gram**6 - 48 * gram**4 + 20 * gram**2 - 4 / 3
        energy = weights @ kernel @ weights
        columns.extend(
            [
                np.eye(5)[upper],
                (energy * np.eye(5))[upper],
            ]
        )
        rows.append(np.stack(columns, axis=1))
        targets.append(cap_matrix(points, weights)[upper])
    return np.concatenate(rows), np.concatenate(targets)


def contact_matrices(points: np.ndarray, weights: np.ndarray):
    gram = points @ points.T
    kernel = 32 * gram**6 - 48 * gram**4 + 20 * gram**2 - 4 / 3
    energy = weights @ kernel @ weights
    moment = np.einsum("n,ni,nj->ij", weights, points, points)
    r = np.zeros((5, 5))
    s = np.zeros((5, 5))
    q = np.array(
        [np.einsum("ni,ij,nj->n", points, matrix, points) for matrix in BASIS]
    )
    for left, first in enumerate(BASIS):
        for right, second in enumerate(BASIS):
            r[left, right] = np.trace(
                ((first @ second + second @ first) / 2) @ moment
            )
            s[left, right] = np.sum(weights * q[left] * q[right])
    identity = np.eye(5)
    i0 = (-32 / 3465 - 2 * energy / 15) * identity + 32 / 165 * r - 128 / 1155 * s
    i1 = (8 / 231 - energy / 5) * identity + 8 / 231 * r + 128 / 1155 * s
    i2 = (96 / 385 - 2 * energy / 5) * identity - 416 / 1155 * r - 64 / 1155 * s
    return [i0, i1, i2], energy


def pole_equator(order: int):
    angles = np.pi * np.arange(order) / order
    equator = np.c_[np.cos(angles), np.sin(angles), np.zeros(order)]
    points = np.vstack([np.array([[0.0, 0.0, 1.0]]), equator])
    weights = np.r_[1 / 3, np.full(order, 2 / (3 * order))]
    return points, weights


def latitude(order: int):
    polynomial = lambda a: 693*a**5-1575*a**4+1260*a**3-420*a**2+54*a-2
    a = brentq(polynomial, 0.421, 8 / 19)
    angles = 2 * np.pi * np.arange(order) / order
    points = np.c_[
        np.sqrt(1 - a) * np.cos(angles),
        np.sqrt(1 - a) * np.sin(angles),
        np.sqrt(a) * np.ones(order),
    ]
    return points, np.full(order, 1 / order)


def robinson():
    points = []
    for zero in range(3):
        other = [index for index in range(3) if index != zero]
        for sign in (1, -1):
            point = np.zeros(3)
            point[other] = [1, sign]
            points.append(point / np.sqrt(2))
    for first in (1, -1):
        for second in (1, -1):
            points.append(np.array([1, first, second]) / np.sqrt(3))
    weights = np.array([184 / 2265] * 6 + [387 / 3020] * 4)
    return np.asarray(points), weights


def kkt_samples():
    samples = [("onb", np.eye(3), np.full(3, 1 / 3)), ("robinson", *robinson())]
    for order in (5, 7, 8, 9, 11):
        samples.append((f"pole{order}", *pole_equator(order)))
    for order in (7, 8, 9, 11):
        samples.append((f"latitude{order}", *latitude(order)))
    return samples


def fit_kkt_cp_identity():
    contact_coefficients = cp.Variable(3, nonneg=True)
    channel_coefficients = [cp.Variable((2, 2), symmetric=True) for _ in range(5)]
    constraints = [matrix >> 0 for matrix in channel_coefficients]
    residuals = []
    exact_design_rows = []
    exact_targets = []
    for name, points, weights in kkt_samples():
        contacts, energy = contact_matrices(points, weights)
        _, mass, cross, position = coupled_mass_position_hessian(points, weights)
        represented = sum(contact_coefficients[index] * contacts[index] for index in range(3))
        for channel, coefficient in zip(CHANNELS, channel_coefficients, strict=True):
            represented += coefficient[0, 0] * cp_image(channel, mass)
            represented += coefficient[0, 1] * cp_image(channel, cross + cross.T)
            represented += coefficient[1, 1] * cp_image(channel, position)
        target = cap_matrix(points, weights) / 2
        upper = np.triu_indices(5)
        numerical_columns = [matrix[upper] for matrix in contacts]
        for channel in CHANNELS:
            numerical_columns.extend(
                [
                    cp_image(channel, mass)[upper],
                    cp_image(channel, cross + cross.T)[upper],
                    cp_image(channel, position)[upper],
                ]
            )
        exact_design_rows.append(np.stack(numerical_columns, axis=1))
        exact_targets.append(target[upper])
        residuals.append(cp.vec(represented - target, order="C"))
        print(name, "E", energy, "cap", np.linalg.eigvalsh(2 * target))
    residual = cp.hstack(residuals)
    problem = cp.Problem(
        cp.Minimize(cp.sum_squares(residual)),
        constraints,
    )
    value = problem.solve(
        solver="CLARABEL",
        tol_gap_abs=1e-11,
        tol_feas=1e-11,
        tol_gap_rel=1e-11,
        max_iter=2000,
    )
    print("cp status", problem.status, "squared residual", value)
    print("contact", contact_coefficients.value)
    for ell, coefficient in enumerate(channel_coefficients):
        print("cp channel", ell, coefficient.value, "eig", np.linalg.eigvalsh(coefficient.value))
    design = np.concatenate(exact_design_rows)
    target = np.concatenate(exact_targets)
    coefficient, _, rank, singular = np.linalg.lstsq(design, target, rcond=None)
    plain_residual = design @ coefficient - target
    print(
        "indefinite span rank/residual",
        rank,
        np.max(np.abs(plain_residual)),
        np.linalg.norm(plain_residual),
        "singular tail",
        singular[-5:],
    )


def fit_mass_contact_identity(samples=100, atoms=6, seed=20260821):
    """Diagnostic for the contact + full quadratic mass-stability bridge."""
    rng = np.random.default_rng(seed)
    rows = []
    targets = []
    upper = np.triu_indices(5)
    for _ in range(samples):
        points = rng.normal(size=(atoms, 3))
        points /= np.linalg.norm(points, axis=1)[:, None]
        weights = rng.dirichlet(np.ones(atoms))
        contacts, energy = contact_matrices(points, weights)
        mass = quadratic_mass_matrix(points, weights, stationary_simplification=True)
        columns = [matrix[upper] for matrix in contacts]
        columns.extend(cp_image(channel, mass)[upper] for channel in CHANNELS)
        columns.extend((np.eye(5)[upper], (energy * np.eye(5))[upper]))
        rows.append(np.stack(columns, axis=1))
        targets.append((cap_matrix(points, weights) / 2)[upper])
    design = np.concatenate(rows)
    target = np.concatenate(targets)
    coefficient, _, rank, singular = np.linalg.lstsq(design, target, rcond=None)
    residual = design @ coefficient - target
    print(
        "mass/contact identity",
        "rank", rank,
        "augmented", np.linalg.matrix_rank(np.c_[design, target], tol=1e-9),
        "max/rms", np.max(np.abs(residual)), np.linalg.norm(residual) / np.sqrt(len(residual)),
        "coeff", coefficient,
        "singular", singular[-4:],
    )


def search_signed_scalar_cap_identity(samples=120, atoms=6, seed=20260822):
    """Can a positive KKT block leave only a scalar good when E<0?"""
    rng = np.random.default_rng(seed)
    rows = []
    targets = []
    upper = np.triu_indices(5)
    for _ in range(samples):
        points = rng.normal(size=(atoms, 3))
        points /= np.linalg.norm(points, axis=1)[:, None]
        weights = rng.dirichlet(np.ones(atoms))
        contacts, energy = contact_matrices(points, weights)
        _, mass, cross, position = coupled_mass_position_hessian(points, weights)
        columns = [matrix[upper] for matrix in contacts]
        for channel in CHANNELS:
            columns.extend(
                [
                    cp_image(channel, mass)[upper],
                    cp_image(channel, cross + cross.T)[upper],
                    cp_image(channel, position)[upper],
                ]
            )
        columns.extend((np.eye(5)[upper], (energy * np.eye(5))[upper]))
        rows.append(np.stack(columns, axis=1))
        targets.append((cap_matrix(points, weights) / 2)[upper])
    design = np.concatenate(rows)
    target = np.concatenate(targets)
    contact = cp.Variable(3, nonneg=True)
    hessian = [cp.Variable((2, 2), symmetric=True) for _ in range(5)]
    scalar = cp.Variable(2)
    vector = [contact]
    for block in hessian:
        vector.append(cp.hstack([block[0, 0], block[0, 1], block[1, 1]]))
    vector.append(scalar)
    coefficient = cp.hstack(vector)
    constraints = [block >> 0 for block in hessian]
    constraints.extend((scalar[0] >= 0, scalar[1] <= 0))
    problem = cp.Problem(
        cp.Minimize(cp.sum_squares(design @ coefficient - target)), constraints
    )
    value = problem.solve(
        solver="CLARABEL", tol_gap_abs=1e-11, tol_feas=1e-11,
        tol_gap_rel=1e-11, max_iter=2000,
    )
    print("signed scalar identity", problem.status, value)
    print("contact", contact.value, "scalar", scalar.value)
    for ell, block in enumerate(hessian):
        print("signed hessian", ell, block.value, np.linalg.eigvalsh(block.value))


def inspect_bad_cap_channel_blocks():
    points, weights = latitude(13)
    cap = cap_matrix(points, weights) / 2
    eigenvalues, eigenvectors = np.linalg.eigh(cap)
    bad = eigenvectors[:, 0]
    _, mass, cross, position = coupled_mass_position_hessian(points, weights)
    print("bad cap scalar", eigenvalues[0])
    for ell, channel in enumerate(CHANNELS):
        block = np.array(
            [
                [bad @ cp_image(channel, mass) @ bad,
                 bad @ cp_image(channel, cross) @ bad],
                [bad @ cp_image(channel, cross.T) @ bad,
                 bad @ cp_image(channel, position) @ bad],
            ]
        )
        print("bad channel block", ell, block, "sym eig", np.linalg.eigvalsh((block + block.T) / 2))


def main() -> None:
    design, target = random_data()
    coefficients, _, rank, singular = np.linalg.lstsq(design, target, rcond=None)
    residual = design @ coefficients - target
    print("shape", design.shape, "rank", rank)
    print("max residual", np.max(np.abs(residual)), "rms", np.linalg.norm(residual) / np.sqrt(len(residual)))
    print("singular tail", singular[-5:])
    for ell in range(5):
        print("channel", ell, coefficients[3 * ell : 3 * ell + 3])
    print("identity, energy identity", coefficients[-2:])
    fit_kkt_cp_identity()
    fit_mass_contact_identity()
    search_signed_scalar_cap_identity()
    inspect_bad_cap_channel_blocks()


if __name__ == "__main__":
    main()
